### PR TITLE
Changed <template> to <ng-template> to eliminate Angular2 warning

### PR DESCRIPTION
**Pull request by FaterW**

### CODE REVIEW

**Comment by carlmon** [comment]
@bikalay please merge

**Comment by Toso82** [comment]
@bikalay  When merge this modify?

**Comment by e-watson** [comment]
@bikalay Excuse me, colleagues: what about Fater's changes merge?

**Review by anuruddha-thennakoon — APPROVED** [review]

**Comment by anuruddha-thennakoon** [comment]
Its better if merge this quickly

**Comment by BearandYoon** [comment]
I have also same warning on my project.
Please merge this change.

**Comment by socx** [comment]
Please kindly merge this change.

**Comment by mscoobby** [comment]
Please merge.

**Comment by bculley** [comment]
Please merge

**Comment by rajavijayavendan** [comment]
Please merge the change as soon as possible.

**Comment by LasithaPrabodha** [comment]
Please do merge

**Comment by alessandrov** [comment]
please do merge

**Comment by alessandrov** [comment]
this warning causes issues while deploying to gae, please merge asap

**Comment by nviospvkuadt** [comment]
please...

**Review by luisgagocasas — APPROVED** [review]

**Comment by luisgagocasas** [comment]
**please do merge**

**Comment by kevcjones-archived** [comment]
Please merge buddy... ng5 is out now.. we want to upgrade

**Comment by kevcjones-archived** [comment]
I've made a fork - merged this and the this [https://github.com/ankosoftware/ng2-bootstrap-modal/issues/49#issuecomment-342558956](https://github.com/ankosoftware/ng2-bootstrap-modal/issues/49#issuecomment-342558956) fix to make it angular5 compatible.

Until  the author returns i'll maintain this one and hopefully can fold anything back into this one. It was do this OR change package, and maybe some of you here can step sideways while we wait. Hopefully its clear enough in the readme, and of course since its a 'forked' repo that i'm not stealing or taking any credit for this authors work. I simply want an error free upgrade 👍 

[https://github.com/kevcjones/angularx-bootstrap-modal](https://github.com/kevcjones/angularx-bootstrap-modal)

[edit] Our branch is actually deviating quite a bit now and we're making some breaking changes but the premise is the same just without Bootstrap dependencies and refactoring code with tests etc. 

[https://github.com/kevcjones/ngx-simple-modal](https://github.com/kevcjones/ngx-simple-modal)

**Comment by celsomtrindade** [comment]
@KevCJones I've noticed your fork doesn't have an `issue` tab. I think it would be a must, since the idea is to keep the project updated. I'll try to keep up with your version until this one get's it's attention back, or just keep rolling with yours.

**Comment by fonsecapontes** [comment]
The author will merge?

**Comment by akhsunna** [comment]
**please do merge**

**Comment by Lizonchik** [comment]
# `please do merge`

**Pull request merged**
